services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "7860:7860"
    env_file:
      - .env
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
