FROM python:3.11-slim-bookworm

COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /usr/src/app
COPY frontend .

EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["python", "-m", "app.interface"]